name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v5

      - name: Build da imagem Docker
        run: docker build -t fullstack-react:ci .
